run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: tab

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - i

  gomnd:
    ignored-files:
      - config.go

issues:
  exclude-rules:
    - linters:
        - funlen
      path: "_test.go"

linters:
  enable-all: true
  disable:
    - wrapcheck
    - gochecknoinits
    - exhaustruct
    - exhaustivestruct
    - nonamedreturns
    - paralleltest
    - testpackage

    # Deprecated.
    - scopelint
    - interfacer
    - maligned
    - golint
    - varcheck
    - deadcode
    - ifshort
    - nosnakecase

    # Disabled because of generics.
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - structcheck
