run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: tab

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - i

  gomnd:
    ignored-files:
      - config.go

linters:
  enable-all: true
  disable:
    - wrapcheck
    - gochecknoinits
    - exhaustruct
    - nonamedreturns

    # Deprecated.
    - scopelint
    - interfacer
    - maligned
    - golint
    - exhaustivestruct
    - varcheck
    - structcheck
    - deadcode
    - ifshort
    - nosnakecase
issues:
  exclude:
    - (version|commit|date) is a global variable
