name: CD
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: "DamianReeves/write-file-action@master"
        with:
          path: /tmp/gpg_key
          write-mode: overwrite
          contents: ${{ secrets.GPG_PRIVATE_KEY }}
      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release
        env:
          GPG_KEY_FILE: /tmp/gpg_key
          NFPM_PACKAGES_DEB_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          NFPM_PACKAGES_RPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
